# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88ec6bc7dcec1af9ab33ac04452f22a48edf198a4a3f8e74bc81b9c820bc3bce075b579a90a0ade398550f948eca365beb284d42ea694eafb5a2964adbef2cd0

test:
  secret_key_base: 4b5596d41528565fd3d41242a2b5359545700cde531952305a8f739f7c9ee2864a300f45440f1529db0a59a0ef20fca5f7aba81010b1d243c1f2ea0c6a83408d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
